### ISSUE TITLE
Getting the backup error - seems Powershell script query

### ISSUE THREAD

**Issue by SujeevPachala** [almenscorner/IntuneCD#106]
**Describe the bug**
Can't backup and it seems a powershell query issue

**To Reproduce**
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/5d0345b5-1bbb-4453-a4e0-79bad8c341ae.sh
Traceback (most recent call last):
  File "/home/vsts/.local/bin/IntuneCD-startbackup", line 8, in <module>
    sys.exit(start())
  File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 313, in start
    count = run_backup(args.path, args.output, exclude, token)
  File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/run_backup.py", line 273, in run_backup
    config_count += savebackup(path, output, exclude, token)
  File "/home/vsts/.local/lib/python3.10/site-packages/IntuneCD/backup_powershellScripts.py", line 68, in savebackup
    decoded = base64.b64decode(script_data["scriptContent"]).decode("utf-8")
  File "/usr/lib/python3.10/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.10/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
##[error]Bash exited with code '1'.

**Comment by SujeevPachala** [comment]
How do I know which one is failing?

**Comment by almenscorner** [comment]
If you run the tool interactively from your terminal it should be the last powershell script that IntuneCD prints
