### ISSUE TITLE
[BUG] Additional API Permission Needed

### ISSUE THREAD

**Issue by Snozzberries** [almenscorner/IntuneCD#142]
**Describe the bug**
Application.Read.All required to update Conditional Access policies.

```
Conditional Access policy not found, creating policy: Office 365 App Control
Traceback (most recent call last):
  File "/home/azureuser/.local/bin/IntuneCD-startupdate", line 8, in <module>
    sys.exit(start())
  File "/home/azureuser/.local/lib/python3.10/site-packages/IntuneCD/run_update.py", line 390, in start
    run_update(
  File "/home/azureuser/.local/lib/python3.10/site-packages/IntuneCD/run_update.py", line 301, in run_update
    diff_count += update(path, token, report, remove)
  File "/home/azureuser/.local/lib/python3.10/site-packages/IntuneCD/update_conditionalAccess.py", line 144, in update
    post_request = makeapirequestPost(
  File "/home/azureuser/.local/lib/python3.10/site-packages/IntuneCD/graph_request.py", line 164, in makeapirequestPost
    raise Exception("Request failed with ", response.status_code, " - ", response.text)
Exception: ('Request failed with ', 403, ' - ', '{"error":{"code":"AccessDenied","message":"Insufficient privileges to create or update policy. Application.Read.All scope is required to add/edit application condition.","innerError":{"date":"2023-10-24T01:39:00","request-id":"4fd42c2e-a702-4623-a639-22de6af1d24a","client-request-id":"4fd42c2e-a702-4623-a639-22de6af1d24a"}}}')
```

**Additional context**
https://github.com/almenscorner/IntuneCD/wiki/Getting-started#azure-ad-app-registration-permissions

**Comment by Snozzberries** [comment]
I don't think there is a way to PR Wiki pages. 

https://github.com/Snozzberries/IntuneCD-Wiki/blob/main/Getting-started.md

**Comment by almenscorner** [comment]
This reminded me of something I’ve been meaning to do, open up the Wiki pages. Check the wiki now, you should be able to edit the page :)

**Comment by Snozzberries** [comment]
Nice! Just updated. Thanks!
