### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShocOne** [almenscorner/IntuneCD#59]
**Describe the bug**
When moving to intunecd 1.1.3 and above the export of Enrollment Status Page configuration fails with error message - Resource not found in Microsoft Graph: https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/497f49b4-890c-4935-9ed1-93b513717d60. Rolling back the version to 1.1.2 successfully exports and completes job run.

**To Reproduce**
Azure devops pipeline yaml task
- task: Bash@3
      displayName: IntuneCD backup
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p "$(Build.SourcesDirectory)/prod-backup"
          IntuneCD-startbackup \
              --mode=1 \
              --output=json \
              --path="$(Build.SourcesDirectory)/prod-backup"
              #--localauth=./auth.json
              #--exclude=assignments
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
      env:
        TENANT_NAME: $(TENANT_NAME)
        CLIENT_ID: $(CLIENT_ID)
        CLIENT_SECRET: $(CLIENT_SECRET)

**Errorlogs from console**
2022-11-02T08:41:19.2899674Z Backing up Autopilot enrollment profile: Windows Autopilot Deployment Profile | User driven enrollment with AADJ
2022-11-02T08:41:19.2900394Z Backing up Autopilot enrollment profile: Windows Autopilot Deployment Profile | User driven enrollment with HAADJ
2022-11-02T08:41:20.9111684Z Backing up Enrollment Status Page: All users and all devices
2022-11-02T08:41:20.9112761Z Backing up Enrollment Status Page: [Global] Autopilot Profile | Production Device | Standard_AAD Join ver2.0
2022-11-02T08:41:20.9114604Z Resource not found in Microsoft Graph: https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/497f49b4-890c-4935-9ed1-93b513717d60
2022-11-02T08:41:20.9867024Z Traceback (most recent call last):
2022-11-02T08:41:20.9868444Z   File "/home/vsts/.local/bin/IntuneCD-startbackup", line 8, in <module>
2022-11-02T08:41:20.9868942Z     sys.exit(start())
2022-11-02T08:41:20.9869690Z   File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 241, in start
2022-11-02T08:41:20.9870261Z     run_backup(args.path, args.output, exclude, token)
2022-11-02T08:41:20.9871222Z   File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 161, in run_backup
2022-11-02T08:41:20.9871828Z     config_count += savebackup(path, output, exclude, token)
2022-11-02T08:41:20.9872643Z   File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/backup_enrollmentStatusPage.py", line 56, in savebackup
2022-11-02T08:41:20.9873526Z     app = {'name': app_data['displayName'], 'type': app_data['@odata.type']}
2022-11-02T08:41:20.9874227Z TypeError: 'NoneType' object is not subscriptable
2022-11-02T08:41:21.0193735Z ##[error]Bash exited with code '1'.
2022-11-02T08:41:21.0203596Z ##[error]Bash wrote one or more lines to the standard error stream.
2022-11-02T08:41:21.0207326Z ##[error]Traceback (most recent call last):
  File "/home/vsts/.local/bin/IntuneCD-startbackup", line 8, in <module>
    sys.exit(start())
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 241, in start
    run_backup(args.path, args.output, exclude, token)
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/run_backup.py", line 161, in run_backup
    config_count += savebackup(path, output, exclude, token)
  File "/home/vsts/.local/lib/python3.8/site-packages/IntuneCD/backup_enrollmentStatusPage.py", line 56, in savebackup
    app = {'name': app_data['displayName'], 'type': app_data['@odata.type']}
TypeError: 'NoneType' object is not subscriptable

2022-11-02T08:41:21.0273554Z ##[section]Finishing: IntuneCD backup

**Run type (Azure DevOps with hosted agent):**
 - Mode: [ci + manual run]
 - Client [ vmImage: ubuntu-latest]
 - Version [intunecd 1.1.3 and 1.1.4]

**Comment by almenscorner** [comment]
Hi,

Can you have a look at the configured apps on the ESP: `[Global] Autopilot Profile | Production Device | Standard_AAD Join ver2.0`?, looks like it's failing to get the app information (497f49b4-890c-4935-9ed1-93b513717d60) added to that ESP configuration.

**Comment by ShocOne** [comment]
Hi there,

I was able to fix the issue by removing the ESP, recreating from scratch and reassigning the apps in the "Block device use until required apps" section. Export now completes with both MSFT app store and win32 apps assigned.

Many thanks

Dafydd

**Comment by almenscorner** [comment]
Thank you for testing and the update. I don't know what might have been the issue with that specific ESP but I will keep an eye out if others runs into the same issue!
