### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by harmmm** [almenscorner/IntuneCD#72]
**Describe the bug**
charmap (I'm using pip 22.3 from C:\Program Files\Python311\Lib\site-packages\pip (python 3.11))  not working as expected when running IntuneCD-startdocumentation on specific characters

**To Reproduce**
Use unicode characters (e.g. U+1F310) in publisher field

**Expected behavior**
Im having Android publishers using certain unicode characters (e.g. U+1F310)

**Screenshots**

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\IntuneCD-startdocumentation.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\IntuneCD\run_documentation.py", line 218, in start
    run_documentation(args.path, args.outpath, args.tenantname, args.jsondata, args.maxlength, args.split, args.cleanup)
  File "C:\Program Files\Python311\Lib\site-packages\IntuneCD\run_documentation.py", line 106, in run_documentation
    document_configs(f'{configpath}/Applications/Android', outpath, 'Android Applications', maxlength, split, cleanup)
  File "C:\Program Files\Python311\Lib\site-packages\IntuneCD\documentation_functions.py", line 290, in document_configs
    md.write(str(config_table) + '\n')
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f310' in position 525: character maps to <undefined>

**Run type (please complete the following information):**
 - Mode: 1
 - Client Pipeline
 - Version 1.2.6

**Comment by basziee** [comment]
https://github.com/almenscorner/IntuneCD/issues/51#issuecomment-1340959764

**Comment by harmmm** [comment]
Ah, what a coincidence :-) Thanks @basziee.

**Comment by almenscorner** [comment]
As @basziee mentioned above, that system variable should let you complete the documentation. There's also improvements coming to the output of the documentation shortly.
