### ISSUE TITLE
[BUG]: IntuneCD-startdocumentation 'TypeError: can only concatenate str (not "dict") to str'

### ISSUE THREAD

**Issue by aaronparker** [almenscorner/IntuneCD#74]
**Describe the bug**
Running IntuneCD-startdocumentation results in 'TypeError: can only concatenate str (not "dict") to str'.

```log
Run INTRO="Microsoft Intune backup and documentation generated at $GITHUB_REPOSITORY <img align=\"right\" width=\"96\" height=\"96\" src=\"./logo.png\">"
  INTRO="Microsoft Intune backup and documentation generated at $GITHUB_REPOSITORY <img align=\"right\" width=\"96\" height=\"96\" src=\"./logo.png\">"
  IntuneCD-startdocumentation \
      --path="$GITHUB_WORKSPACE/prod-backup" \
      --outpath="$GITHUB_WORKSPACE/prod-as-built.md" \
      --tenantname=$TENANT_NAME \
      --intro="$INTRO"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TENANT_NAME: ***
    CLIENT_ID: ***
    CLIENT_SECRET: ***
Traceback (most recent call last):
  File "/home/runner/.local/bin/IntuneCD-startdocumentation", line 8, in <module>
    sys.exit(start())
  File "/home/runner/.local/lib/python3.10/site-packages/IntuneCD/run_documentation.py", line [2](https://github.com/aaronparker/intune-backup/actions/runs/3644379916/jobs/6153567987#step:10:2)18, in start
    run_documentation(args.path, args.outpath, args.tenantname, args.jsondata, args.maxlength, args.split, args.cleanup)
  File "/home/runner/.local/lib/python[3](https://github.com/aaronparker/intune-backup/actions/runs/3644379916/jobs/6153567987#step:10:3).10/site-packages/IntuneCD/run_documentation.py", line 129, in run_documentation
    document_configs(f'{configpath}/Device Configurations', outpath, 'Configuration Profiles', maxlength, split, cleanup)
  File "/home/runner/.local/lib/python3.10/site-packages/IntuneCD/documentation_functions.py", line 2[4](https://github.com/aaronparker/intune-backup/actions/runs/3644379916/jobs/6153567987#step:10:4)4, in document_configs
    for key, value in zip(repo_data.keys(), clean_list(repo_data.values())):
  File "/home/runner/.local/lib/python3.10/site-packages/IntuneCD/documentation_functions.py", line 18[5](https://github.com/aaronparker/intune-backup/actions/runs/3644379916/jobs/6153567987#step:10:5), in clean_list
    values.append(dict_string(item))
  File "/home/runner/.local/lib/python3.10/site-packages/IntuneCD/documentation_functions.py", line 14[7](https://github.com/aaronparker/intune-backup/actions/runs/3644379916/jobs/6153567987#step:10:7), in dict_string
    first = '<br />&nbsp;&nbsp;&nbsp;&nbsp; - &nbsp;' + v[0]
TypeError: can only concatenate str (not "dict") to str
Error: Process completed with exit code 1.
```

**To Reproduce**
See commands used in the log extract above.

**Expected behavior**
Markdown documentation should complete.

**Run type (please complete the following information):**
 - Mode: 1
 - Client: GitHub Actions
 - Version: 1.2.7

**Comment by almenscorner** [comment]
Can you verify that you are running the latest version? that error looks like it's coming from v 1.2.6

**Comment by aaronparker** [comment]
I've re-run it and it's completed OK. Thought the pipeline had run post 1.2.7 being published.
